### ISSUE TITLE
Flash Messages

### ISSUE THREAD

**Issue by davidhuser** [Rhym/cakeStrap#6]
Could you tell me how to show the flash messages? The messages appear in plain text in the view, but without loading the flash messages of Twitter Bootstrap.

**Comment by protetore** [comment]
I'm having the same problem here.

**Comment by shivasd** [comment]
I have the same problem.

**Comment by ghost** [comment]
Same here

**Comment by jlpuder** [comment]
You'll have to modify the controller displaying the messages. Since there isn't a way to have custom output for controllers via the bake script, you'll have to edit it yourself.

For example:

``` php
//Default line from controller after using the bake console
$this->Session->setFlash(__('The user has been saved'));
//Edited line to use the success styling
$this->Session->setFlash(__('The user has been saved'), 'flash/success');
```

This will use the success.ctp template under Cakestrap/Elements/flash. Just replace it with error or info where appropriate.
http://book.cakephp.org/2.0/en/core-libraries/components/sessions.html#creating-notification-messages
